### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by belev**
* Use `let` instead of `var`
* Use `'` instead of `"`
* Add missing semicolons
* Add new line at files end
* Add missed imports from `rxjs`

The codelyzer is giving errors for missed whitespace between variable name and its type but I see that this is used almost everywhere in the project. Should I fix that?

### CODE REVIEW

**Comment by pgergov** [comment]
Yo @belev thanks for the PR :beer: 

Few things to have in mind:
The project was under heavy development in the last two weeks & that's why I didn't merge your PR. Atm the state is kinda stable, most of the required features are done & if you wan't you can make another `Lint fix` PR since this one has 'a few' conflicts.

Also, if you have any `Angular 2` related comments I'm open for discussion since this is my first NG2 application and I'm still lacking experience with it.

**Comment by belev** [comment]
@pgergov No problem for the delay. No need to create new pull request, I resolved the conflicts and fixed some more lint errors. You can review the PR now.

I am not `Angular 2` expert so I don't think I can say much. For the production build you can check AoT, in the latest version of `angular-cli` it is supported. It is working also, I tried it a few weeks ago. The command should look like this: `ng build --prod --aot --env=prod`.

**Comment by pgergov** [comment]
@belev Could you fix the conflicts? Few more emerged :panda_face:

**Comment by belev** [comment]
@pgergov Sure, I will fix them now.

**Comment by belev** [comment]
@pgergov Done :white_check_mark:

**Comment by pgergov** [comment]
@belev Merged.

Btw, what's that hype around using `let` everywhere? If I (as a developer) know that I can do the job with `var` what's the problem using it?

**Comment by belev** [comment]
It is related to the scope. `var` is scoped to the nearest function scope and `let` to the nearest enclosing block scope. However if you don't like the usage of `let` you can disable the linting rule for `var`: [from your tsconfig](https://github.com/HackSoftware/HackFMI-NG2/blob/master/tslint.json#L55).

**Comment by pgergov** [comment]
Yeah, I know the difference between `let` & `var`. My question tho was "Is it some kind of convention in the JS world to use `let` all around"?

**Comment by belev** [comment]
Ah, ok. I don't understand you but I can't give you an answer for that.

**Pull request merged**
